[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy-Report-Only = "default-src 'self'; base-uri 'self'; img-src 'self' ; object-src 'none'; script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com; style-src 'self' https://fonts.googleapis.com; form-action 'self'; font-src https://fonts.gstatic.com; child-src https://youtube.com; frame-src https://www.youtube.com; frame-ancestors 'self'"
