[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; connect-src https://www.google-analytics.com; form-action 'self'; style-src 'self' fonts.googleapis.com; script-src 'self' https://www.googletagmanager.com; font-src fonts.gstatic.com; child-src https://youtube.com; frame-src https://youtube.com; frame-ancestors self;"
